### PR TITLE
adds .travis.yml file

### PR DESCRIPTION
**Pull request by cubadomingo**

### CODE REVIEW

**Comment by tmobaird** [comment]
Looks like a minitest problem. For some reason `bundle exec rake` is running minitest instead of rspec

**Comment by tmobaird** [comment]
Shoot wait this is going to fail until we have a spec directory set up. Did you want to do this or did you want me to?

**Comment by tmobaird** [comment]
you might also need to change the script from `bundle rake rspec` to `bundle rake spec`

**Comment by cubadomingo** [comment]
Hey bro, I installed the spec folder just now. I think you're right about changing it to <bundle rake spec>. Let me see if it fails and I'll get to it.

**Comment by tmobaird** [comment]
NOW WE'RE IN BUSINESS!!! Nice job dude!! 👍 👍 👍

**Comment by cubadomingo** [comment]
Whooo! I'll add the build button to the read me right now too.

**Comment by tmobaird** [comment]
Looks great bro

**Pull request merged**
