### PR TITLE
adds regions controller and views, along with routing

### LINKED ISSUE #32: Page after user signs in
Alright so here's what I'm thinking after the user is able to sign in:

It should redirect to a page that looks like this:
screen shot 2016-07-28 at 7 08 42 pm

Don't mind the double posts and events, or fonts, just an example. I'm thinking we change the navbar once in the feed page to make it look like the one in the example. The links should be the different categories and in the side there should be links to filter the posts and events, along with genres (for the music category atleast). Now this is the page that I'm thinking we do using React. So the initial page load should be rendered on the server side and then all the updating on the page should be client side.

I'm thinking the navbar, user settings and account section should be traditional rails erb, as well as the individual posts themselves.

What do you think about this idea? Let me know if it makes sense or if I'm talking out of my ass, cause I'm still trying to understand react myself haha.

### LINKED ISSUE #42: User Profile?
We might need to add some form of user profile or explore page. We need something that allows the users to add cities and regions to their lists so that we can aggregate posts and events for their feed.

Not sure what the best way to do this would be.

### LINKED ISSUE #45: Navbar after user logs in and CSS for feed page

### PR DESCRIPTION
**Pull request by cubadomingo**
A couple of things I did here. I updated the routes to correspond to the navigation in the README.

also I have the navbar finished. closes #45, closes #42,  closes #32 

I also added the regions controller, and the views.

I currently have the region feed set to `/region/feed` but I want it to work as such `/washingtondc/feed`. Have any ideas on how to implement this?

### CODE REVIEW

**Comment by tmobaird** [comment]
So the general rails way to do this is have it be something like `regions/region_id/feed` but if you wanted to add the region name in there you could always look into something like this:

http://stackoverflow.com/questions/31262631/in-url-how-to-show-title-name-instead-of-id-in-ruby-on-rails

**Comment by cubadomingo** [comment]
I'm currently using friendly_id with my blog for the posts names, so this is exactly what I was thinking about doing. I'm going to try to implement this and keep you posted.

**Comment by tmobaird** [comment]
sounds good. I see a couple really small things that were added that I want to clean up a little bit. Mind if I take a stab at these?

**Comment by tmobaird** [comment]
Other than that this PR was dope!

**Comment by cubadomingo** [comment]
Thanks brother 👊

**Comment by cubadomingo** [comment]
My bad I missed your first comment, but yeah bro absolutely go for it!

**Pull request merged**
