### PR TITLE
creates rsvp model and associations

### PR DESCRIPTION
**Pull request by cubadomingo**
Hey bro so I completely got sidetracked and forgot about implementing the RSVP model. Could you possible look at the associations and make sure they're okay? I don't feel too good about the User model having:
`has_many :events`
and
`has_many :rsvps`
 `has_many :events, through: :rsvps`

I feel like has_many shouldn't be there twice for the events.

### CODE REVIEW

**Comment by cubadomingo** [comment]
Fuck I just realized that in the migration I accidentally put patient and physician as I was looking at the Rails associations guide. I gotta fix that.

**Comment by tmobaird** [comment]
lol it's all good. did you want me to fix it? or were you gonna do it?

Also it's probably best to remove the line `has_many :events, through: rsvps`

I would probably create a User model method `rsvped_events` or `attending_events` that looks something like this:

```ruby
def rsvped_events
  rsvps.map { |x| x.event }
end
```

That's not super efficient, but should work. Not sure if this will work, but you might be able to try this:

```ruby
has_many :rsvped_events, through: :rsvps, source: :events
```

**Comment by tmobaird** [comment]
I just tested out the second way and it looks like it should work with this:

```ruby
has_many :rsvped_events, through: :rsvps, source: :event
```

This should work as long as the belongs to relationships are set up properly in the model and migrations

**Comment by cubadomingo** [comment]
Right on bro, thanks for the help. I'll tackle it first thing tomorrow morning.

**Pull request closed without merging**
