### PR TITLE
adds sign in view and landing page view, also sets landing page to root

### PR DESCRIPTION
**Pull request by cubadomingo**

### CODE REVIEW

**Comment by cubadomingo** [comment]
Failing because I changed log in to sign in. Also I removed the Devise error messages as I planned to make them flash messages, which is also causing another fail. Hooray for testing. I'll get to it.

**Comment by tmobaird** [comment]
Sounds good. Let me know if you need any help with it dude!

**Comment by tmobaird** [comment]
Did you want me to help out with adding the flash alerts? I have a sample erb file that's pretty good at handling most flash alerts in a rails app.

**Comment by cubadomingo** [comment]
I haven't had time to work on that, so if you could that would be awesome brother!

**Comment by tmobaird** [comment]
I probably won't be able to get to this til 3 or 4. So feel free to knock this out if you've got the time!

**Comment by cubadomingo** [comment]
I think I'm going work on the mailer, currently it's just an input that does nothing, and also adding SSL, and finally trying to get that landing page in deployment  So I'll let you take care of the flash messages, and no worries bro whenever you can.

**Comment by tmobaird** [comment]
Sounds good. I'll update this PR when I get a chance.

**Comment by cubadomingo** [comment]
Thanks bro ✊

**Comment by tmobaird** [comment]
@cubadomingo I've got some code ready for this if you want me to push it up

**Comment by tmobaird** [comment]
This PR should be good to go now 👍

**Comment by cubadomingo** [comment]
Good stuff bro! I'm just about finishing adding the subscriber form along with specs (it was just an input and button that didn't do anything.) and it should be good to deploy. I'll keep you updated.

**Comment by tmobaird** [comment]
@cubadomingo thanks bro 👍

**Pull request merged**
