### PR TITLE
Facebook oauth

### PR DESCRIPTION
**Pull request by tmobaird**
Yo dude take a look at this when you get a chance. So I added the facebook omniauth functionality to devise and it seems to be working properly. I'm gonna need to style the UI for the registration and sign in pages at some point and I also want to create a mailer for new sign-ins.

I also deleted the bootstrap sprockets line from application.js because it was causing an error when I ran my server locally, and was working for me after I made that change. 

Some of the changes in this are merge conflict resolutions, this branch is already rebased on master so it should be good to merge in.

### CODE REVIEW

**Comment by cubadomingo** [comment]
I can take care of the UI for the registration and sign in pages. Everything looks good bro, good job!

**Comment by tmobaird** [comment]
Thanks dude. And you might need to generate the devise login views with a devise command. I believe as default they are hidden inside the gem, but I believe them have a command in their docs that will copy them to your views folder

**Comment by cubadomingo** [comment]
yup used:
`rails generate devise:views`

thanks for the heads up.

**Comment by tmobaird** [comment]
Yup, nice brotha! :+1:

**Pull request merged**
