### PR TITLE
Adds various changes

### PR DESCRIPTION
**Pull request by cubadomingo**
Okay so I removed the react-rails gem I installed by error and installed the proper gem: react-on-rails, as well as other small minor changes. I haven't had too much time to dive into the gem and see how it works but there's a default Hello component that shows up and appears to be working.
screen shot 2016-07-29 at 8 52 59 am

Apparently it adds a client folder where all the components are stashed in, but if you take a look at their documentation it has all you need, it's pretty comprehensive. #32

### CODE REVIEW

**Comment by tmobaird** [comment]
Did you have to run the server in any different way to work with react? Or could you simply just run the rails server and the react components will work?

**Comment by tmobaird** [comment]
These changes look good though from what I know so far about React on rails. I think I pretty much have the hang of React so I'm gonna take a crack at adding a component over the next couple of days for a region's event list. 

I'll probably first need to create some controller actions and things like that. We should probably create an interface somewhat soon for creating events and posts, but that's not necessary yet. 

I think I have a general idea of how to start with the React component, so I can give this a crack if you want me to

**Comment by cubadomingo** [comment]
Okay finally got this to work on Travis, whooo! So here's what I had to do to get react to work:
screen shot 2016-07-29 at 9 56 19 am

But on my localhost it wasn't port 3000, it was actually localhost:5000. It might be different for you, just check the server on terminal when you start foreman for the port.

**Comment by cubadomingo** [comment]
Yeah bro, go for it!! I'll jump in once I feel a bit more confident.

**Comment by tmobaird** [comment]
yeah it was port 5000 for me to get it to work. Any idea how to get this to deploy and work?

**Comment by cubadomingo** [comment]
No clue yet, I'll read the docs but if I can't figure it out, I'm on the slack channel with the shakacode dev team 🙂, so don't worry I'll find out!

**Comment by tmobaird** [comment]
👍 you da man!

**Pull request merged**
