### PR TITLE
css revamp

### PR DESCRIPTION
**Pull request by cubadomingo**
So I decided to just revamp the whole styling for the site. Let me know what you think.
screen shot 2016-08-07 at 5 46 20 pm
screen shot 2016-08-07 at 5 48 07 pm

Also I integrated the bootstrap navbar again, so it's collapsible now.

### CODE REVIEW

**Comment by tmobaird** [comment]
It's all good bro. I'll take a look in a little bit when I get to my cpu

**Comment by cubadomingo** [comment]
Fasho bro, much appreciated.

**Comment by tmobaird** [comment]
this should be good to go now. Just some stuff needed updated in the tests. Also, I really like the new styles dude! Looks sick!

**Comment by cubadomingo** [comment]
It wasn't removed bro, I was messing around with the root and forgot to set it back. Thanks for the help brother!

**Pull request merged**
