### PR TITLE
css styling additions

### PR DESCRIPTION
**Pull request by cubadomingo**
Just some minor things. I extended the individual post and event column to 12 so it spans the width of the page. It looks odd because there really is no content. I also plan on adding a side navbar there maybe. Still working on that.

### CODE REVIEW

**Comment by tmobaird** [comment]
The build failed because some of the tests failed because the class `btn-primary` were removed from a view or two. This is what the test tries to find, so you should just be able to update the tests with the new class

**Comment by cubadomingo** [comment]
Yeah bro, what I was trying to do was see if we could keep the functionality but just by clicking the glyphs without buttons so it looks a bit cleaner. You think that would be possible or would you rather we keep the buttons?

**Comment by tmobaird** [comment]
Wait so you just want the glyphs to function as the clickable components for the other fields to appear? If so, I can do that. I just need to update the react a little bit

**Comment by cubadomingo** [comment]
Well I'm referring to the like, dislike button, so a + would be a like and a - would be a dislike button, and I guess have the glyph change color if it's clicked just like you were doing it with the button.

**Comment by tmobaird** [comment]
Yeah, let me see if I can do this. I think I can

**Comment by tmobaird** [comment]
actually I don't know if this is possible. I believe button_to creates a button element as default

**Comment by cubadomingo** [comment]
What if we were to do a link_to. BTW, I completely scratched off this PR it's a mess.

**Comment by tmobaird** [comment]
I was attempting to use link_to but for some reason this isn't allowing me to link to a delete or post action

**Comment by cubadomingo** [comment]
That's odd. You were passing the `method: :delete` option right?

**Comment by tmobaird** [comment]
yep

**Comment by tmobaird** [comment]
not sure what was the problem

**Comment by cubadomingo** [comment]
Ahh you know it might be a javascript issue. I think when you first implemented that feature we had removed JQuery from application.js

**Comment by tmobaird** [comment]
I think you might be right

**Comment by cubadomingo** [comment]
screen shot 2016-08-09 at 9 24 00 pm
Just tested it, and this works

**Comment by tmobaird** [comment]
hell yeah, that looks sick dude

**Comment by cubadomingo** [comment]
I'll fix it up. That make so much sense now. the button_to was confusing the hell out of me haha

**Pull request closed without merging**
