### PR TITLE
sign in/sign up view merger

### PR DESCRIPTION
**Pull request by cubadomingo**
Alrigh bruh bruh, so I was finally able to get the the sign in/sign up view working properly. Here's everything I did:

- merged sign in/sign in views. I fixed up the css and everything.

- applied sign in redirect to the user feed

- applied sign out redirect to the user feed

- applied sign up redirect to the user feed

- created a `SessionsController` that inherits from the `Devise::SessionController`

- created a `RegistrationController` that inherits from the `Devise::RegistrationController`

Overall I'm pretty impressed with how easy it is to customize Devise, once you view their controllers source code of course. Gotta love how self expressing ruby code.

### CODE REVIEW

**Comment by cubadomingo** [comment]
So it's probably the sign in/sign out features that are failing. I'll fix that right now.

**Comment by tmobaird** [comment]
I'd probably leave the redirect after sign in and sign out to the root for the time being. The feed will eventually become the root path once we go live, so it's probably best just to go to root

**Comment by tmobaird** [comment]
And yeah, I bet the specs are failing because in the change of the html elements. No worries dude just update them to reflect the new style and let me know if you need help :+1:

**Comment by cubadomingo** [comment]
Okay specs aren't failing locally so it should be good.

I thought the explore page was going to be set for root when we add more regions but for the meantime the Washington DC metro feed would stay as the root. So even though the user feed will still be washington dc metro feed as default I think we should appropiately route it to /feed instead of /washington-dc-metro-area/feed.

That way visitors are able to visit automatically the Washington DC Feed, but it won't show their subscriptions, but now a User that logs in gets routed to their subscribed feeds. This doesn't matter for a while I suppose until regions get added but I think there's no harm in having it set now.

Thoughts?

**Comment by cubadomingo** [comment]
Speaking of subscriptions. How should we let a user pick a default region when signing up? For now I think we should set it in the controllers but once we add regions maybe like a drop down list? or a react search bar where cities automatically get displayed. What do you think?

**Comment by tmobaird** [comment]
Ok, your idea on the redirecting sounds good. And hmm the react search bar sounds great! But lets put that on the backlog since that's more difficult. We could always redirect them to their feed and say something like `your feed is empty, subscribe to a location` and have a button that'll link to the explore page where they can subscribe to any

**Comment by cubadomingo** [comment]
Yeah no doubt. Those are great ideas too. We're still quite a while away from implementing that so you're right we'll put that on the backlog.

**Comment by tmobaird** [comment]
nice work bro!! :+1: :ok_hand: :100:

**Pull request merged**
