### PR TITLE
Update devise views

### LINKED ISSUE #14: Format Sign Up and Forgot Password Pages Similar to Sign In
Currently the Sign In page is the only properly formatted and styled devise view. The Sign Up and Forgot Password pages both need updated to reflect the site's desired style.

### PR DESCRIPTION
**Pull request by tmobaird**
Closes #14. Rebased and all tests pass locally.

Also I think we should eventually add the coverage directory to our .gitignore file, it's probably not needed in the repo.

### CODE REVIEW

**Comment by tmobaird** [comment]
I believe this coverage is correct now. I changed it to track for a Rails app.

**Comment by cubadomingo** [comment]
Bro, I had absolutely no clue what I was doing with coveralls hahaha. I was thinking like no way this is at 100%. Could you just give me a real quick explanation of what you did to make it track a rails app?

**Comment by tmobaird** [comment]
lol yeah man. So in the rails_helper.rb you added the line:

```ruby
Coveralls.wear!
```

That's fine for most projects, but that will just track every file that runs in a project for, I believe. I simply had to change that line to:

```ruby
Coveralls.wear!('rails')
````

so it will track the files as a rails app.

**Comment by cubadomingo** [comment]
Ahh I see. Good to know. Also I went ahead and added the directory to the gitignore and the sign up and forgot password views look great man. Awesome job 👏

**Pull request merged**
