### PR TITLE
Capistrano fix

### PR DESCRIPTION
**Pull request by cubadomingo**
Just some minor tweak. Also updated React_on_rails to the latest version. Localhost is now at :3000 for the react components.

### CODE REVIEW

**Comment by tmobaird** [comment]
do we still have to run our server with the foreman command?

**Comment by cubadomingo** [comment]
you can use `npm run rails-server`

Since the sample hello world is running with npm modules it needs to run on a node server.

**Comment by tmobaird** [comment]
sounds good 👍 feel free to checkout user-feed branch and checkout what i've got so far. Super basic, figuring out the controller methods now, then moving on to react components

**Comment by cubadomingo** [comment]
Looks great so far bro 👍

**Pull request merged**
