### PR TITLE
adds gem, specs, and subscriber model

### PR DESCRIPTION
**Pull request by cubadomingo**
So I did a couple of things here:

- added Shoulda Matchers gem

- added Subscriber model, with validations and feature specs and model spec

- created a factory for the Subscriber model

I'm no expert in testing so if you could just go over it and give me some feedback that would be great. Also I don't have the mailer implemented yet as I'm waiting for Mailgun to approve the domain records. Should be done by tomorrow, but at least people are able to subscribe with their email now!

I also added a regex validator in the subscriber model for the email and it's working but instead of receiving a flash message, it's not even letting me submit the form as it's being blocked by a HTML 5 form validation, is that a feature that you added? If not I think I read somewhere that Rails 5 now does client side validation, though I'm not too sure. Anyways I have no clue how to test for that but it's visible in a manual test. The sign in page also has the same client side validation for email.

Also, testing doesn't feel like a drag anymore haha.

### CODE REVIEW

**Comment by tmobaird** [comment]
Lol nice dude! You've been crushing it lately! I'll take a look at this in a little bit and get you some feedback :+1:

**Comment by cubadomingo** [comment]
Right on, thanks and whenever you can, no rush homie.

**Comment by tmobaird** [comment]
Wait, so were you just going to use Mailgun instead of ActionMailer for the email service? 

I also didn't know that, but it definitely looks like `form_form` adds client side validation in the views. That's pretty awesome! 

Also the tests look good! I do see a couple issues though:

1. The formatting in the Shoulda-matchers block in the rails_helper.rb file is indented incorrectly. Lines 71-76 should be indented two spaces to make the DOs and ENDs line up.
2. There probably shouldn't be able to be multiple Subscribers with the same email address. You should probably add this line to the Subscriber model: 

```ruby
validates_uniqueness_of :email
```

This update will cause you to have to update a couple things in the Subscriber Factory and feature spec. Line 3 of the subscriber factory file should look something like this:

```ruby
sequence(:email) { |x| "test.user#{x}@gmail.com" }
```

This sequence means that every time a new subscriber factory is created, the email will increment the value for x. Ex. first subscriber created will have email "test.user1@gmail.com", second subscriber created will have email "test.user2@gmail.com".

This uniqueness update will also mean you'll have to update the `spec/features/subscribe_spec.rb` file. The first example will not work because line 2 will effectively create a new subscriber before every example, meaning that if you were to fill out the form based upon this already created subscriber's email, the test would fail because this would violate the uniqueness validation.

That being said, the second example in this file will still pass. Another good test, if you're feeling 💯  with your testing, might be to add a test that validates that you can't subscribe when a subscriber has already been created with the email you enter.

**Comment by tmobaird** [comment]
Sorry, I know that was a lot to read. Let me know if you need help with any of those changes.

**Comment by cubadomingo** [comment]
Alright bro I went ahead and corrected the issues. I also added a flash message when a user is already subscribed along with the feature spec for it. Looks like all tests have passed so I'm going to merge.

Also I didn't know about the sequence method with factories but seems very useful. Learning more everyday! Thanks for checking my work bro ✊

**Comment by tmobaird** [comment]
No problem. Nice job brotha 👍 good work!

**Pull request merged**
